<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10797" started-at="2020-04-29T12:47:04 IST" finished-at="2020-04-29T12:47:15 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10797" started-at="2020-04-29T12:47:04 IST" finished-at="2020-04-29T12:47:15 IST">
      <class name="services.IncidentTests">
        <test-method status="PASS" signature="setUpReuqest()[pri:0, instance:services.IncidentTests@15deb1dc]" name="setUpReuqest" is-config="true" duration-ms="1750" started-at="2020-04-29T12:47:02 IST" finished-at="2020-04-29T12:47:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpReuqest -->
        <test-method status="FAIL" signature="createIncident()[pri:0, instance:services.IncidentTests@15deb1dc]" name="createIncident" duration-ms="10448" started-at="2020-04-29T12:47:04 IST" finished-at="2020-04-29T12:47:14 IST">
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[java.util.ArrayList cannot be cast to java.lang.String]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
at services.IncidentTests.createIncident(IncidentTests.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createIncident -->
        <test-method status="SKIP" signature="deleteIncident()[pri:0, instance:services.IncidentTests@15deb1dc]" name="deleteIncident" duration-ms="0" started-at="2020-04-29T12:47:15 IST" depends-on-methods="services.IncidentTests.createIncident" finished-at="2020-04-29T12:47:15 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method IncidentTests.deleteIncident()[pri:0, instance:services.IncidentTests@15deb1dc] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method IncidentTests.deleteIncident()[pri:0, instance:services.IncidentTests@15deb1dc] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteIncident -->
      </class> <!-- services.IncidentTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
